#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# PATH
export PATH="$PATH"":${HOME}/.local/bin/"

# genie for wsl2
 if [ "`ps -eo pid,lstart,cmd | grep systemd | grep -v -e grep -e systemd- | sort -n -k2 | awk 'NR==1 { print $1 }'`" != "1" ]; then
  genie -s
fi

# Function
find "${HOME}"/bin/functions/ -type f | while read line; do source "${line}"; done

# bind
bindkey "jj" vi-cmd-mode

# EDITOR
export EDITOR='vim' # nanoからvimに変更
export VISUAL='vim' # nanoからvimに変更
export PAGER='less'

# History
HISTFILE=$HOME/.zsh-history
HISTSIZE=100000
SAVEHIST=1000000

# share .zshhistory
setopt inc_append_history
setopt share_history

# ssh-agent
SSH_KEY_LIFE_TIME_SEC=3600
SSH_AGENT_FILE="$HOME/.ssh/ssh-agent"
test -f "$SSH_AGENT_FILE" && source "$SSH_AGENT_FILE" >/dev/null 2>&1
if [ $(ps -ef | grep ssh-agent | grep -v grep | wc -l) -eq 0 ]; then
  ssh-agent -t $SSH_KEY_LIFE_TIME_SEC >|"$SSH_AGENT_FILE"
  source "$SSH_AGENT_FILE" >/dev/null 2>&1
fi

ssh-add ${HOME}/.ssh/${HOST}_id_rsa
